import localFont from "next/font/local";
import "./globals.css";

const champFont = localFont({
  src: "../fonts/Champ-Black.woff2",
  variable: "--font-champ",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr" className={champFont.variable}>
      <body>
        <div className="flex max-h-screen max-w-screen flex-col items-center justify-center min-h-screen bg-primary text-accent p-4">
          {children}
        </div>
      </body>
    </html>
  );
}
